version: "3.8"

services:
  app:
    build: .
    container_name: crypto-metrics-app
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus 
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prom_data: 
